### ISSUE TITLE
[NEW ROUTE] Aszód to Rétság

### ISSUE THREAD

**Issue by nbali** [Sp3EdeR/huroutes#10]
"Munkaanyag cruising tervezéshez :-) [...] de gondoltam kiteszem, mert marha jó útvonal, akár szólóban is. A héten végimentem rajta motorral (ismét), hogy nehogy hülyeséget mondjak... A legkényesebb autotulajok is jöhetnek, csak nem szabad letérni róla, mert vannak szántásnak is göröngyös részek, pl. ősagárd felé...

[https://www.google.hu/maps/dir/Asz%C3%B3d/47.7970368,19.3815139/Keszeg/R%C3%A9ts%C3%A1g,+2653/@47.7617682,19.3996006,11z/data=!4m21!4m20!1m5!1m1!1s0x4741ca83dab5f2a5:0x5e3ca016ca216a41!2m2!1d19.4843422!2d47.6533802!1m0!1m5!1m1!1s0x474029384b6037e9:0xc94e0e8e22539038!2m2!1d19.2388746!2d47.8366001!1m5!1m1!1s0x476a9ce2edaed803:0x341126266c66c88b!2m2!1d19.1473296!2d47.9405312!3e0](https://www.google.hu/maps/dir/Asz%C3%B3d/47.7970368,19.3815139/Keszeg/R%C3%A9ts%C3%A1g,+2653/@47.7617682,19.3996006,11z/data=!4m21!4m20!1m5!1m1!1s0x4741ca83dab5f2a5:0x5e3ca016ca216a41!2m2!1d19.4843422!2d47.6533802!1m0!1m5!1m1!1s0x474029384b6037e9:0xc94e0e8e22539038!2m2!1d19.2388746!2d47.8366001!1m5!1m1!1s0x476a9ce2edaed803:0x341126266c66c88b!2m2!1d19.1473296!2d47.9405312!3e0)"

**Comment by Sp3EdeR** [comment]
Ez az útvonal már elkészült.
