### ISSUE TITLE
[NEW ROUTE]  Egerbakta -> Bükkszék -> Pétervására

### ISSUE THREAD

**Issue by nbali** [Sp3EdeR/huroutes#12]

**Comment by Sp3EdeR** [comment]
Megvan itt: https://github.com/Sp3EdeR/huroutes/commit/9a71e17802bcc9f6ee916d1f0418d049d3b2006e

**Comment by nbali** [comment]
Nem teljesen. Egerbakta -> Bükkszék se egy förtelmes szakasz, és az még nincs kész.

**Comment by Sp3EdeR** [comment]
Nekem jó teljesen, csak 1 ticketet próbáljunk egy szakaszosra csinálni. Anélkül a térképen is összefolynak egymásba, és nem lehet normálisan rajzolni. Bejáróutakat majd rakhatunk a háttérbe javasolt összefűzésekhez utána. (Egyébként azok is könnyen összefolynak.)

**Comment by nbali** [comment]
Az egy szakasz volt :) A településeket leszámítva nincs benne szünet. Amit te csináltál az Egerbe megy Egerbakta után. Amiről eredetileg az issue szólt az a nyomvonal az ott északra fordul.

**Comment by Sp3EdeR** [comment]
Na, de ott van egy gyakori elágazási pont. Általában inkább Eger irányába megyünk a Bükk felé, vagy Balaton irányába. Esetleg gyakran visszafordulás van. A Bajna-Héreg szakaszhoz is hozzá lehetne kötni jó pár egybefüggő útalternatíva opciót és akár meg lehetne rajzolni 5× is. Szét kell vágni a lehetőségeket. Mondhatnám, osztályozni kell, hogy kijőjjön egy értelmes modell :)
