### ISSUE TITLE
[ROUTE]: Pilisszentkereszt - Pilisszántó - Pilisvörösvár

### ISSUE THREAD

**Issue by Dpx86** [Sp3EdeR/huroutes#133]
### The route's name / Az út neve

Pilisszentkereszt - Pilisszántó - Pilisvörösvár

### The route / Az út

https://goo.gl/maps/dBoraUMzsspFHSKG9

### The route's description / Az útvonal leírása

Keskeny, nem túl jó ütminőségű, de gyors átkötő út a Dobogókői és a 10-es út között.

### Rating / Értékelés

3

### Last driven / Legutóbbi vezetés

2022.10.10

### The route's type / Az útvonal típusa

- [ ] Route is shown in the background / Háttérben mutatott útvonal

**Comment by Sp3EdeR** [comment]
hhmm viszont ha csak 3 pontos és nem is jó, akkor van értelme felvenni a térképre? Inkább bejáróutakat szoktunk felvenni ha valami nagyobb túrát javasolnánk.
