### ISSUE TITLE
[ROUTE UPDATE] Sirok -> Egerbakta

### ISSUE THREAD

**Issue by nbali** [Sp3EdeR/huroutes#47]
2021-es felújítással frissíteni ( see comments https://github.com/Sp3EdeR/huroutes/commit/9a71e17802bcc9f6ee916d1f0418d049d3b2006e )

**Comment by Sp3EdeR** [comment]
Frissítve: ee98547650cc09e1a5fbc198a6f3c2a0788e3c08
