### ISSUE TITLE
[NEW ROUTE] Bakony, Tés - Olaszfalu

### ISSUE THREAD

**Issue by Sp3EdeR** [Sp3EdeR/huroutes#48]
### The route's name / Az út neve

Tés - Olaszfalu

### The route / Az út

csatolva

### The route's description / Az útvonal leírása

unknown

### The route's type / Az útvonal típusa

- [ ] Route is shown in the background / Háttérben mutatott útvonal

**Comment by Sp3EdeR** [comment]
[Tés - Olaszfalu.zip](https://github.com/Sp3EdeR/huroutes/files/8035007/Tes.-.Olaszfalu.zip)

**Comment by Sp3EdeR** [comment]
> 30-as tábla van kint. Néhol saras, mert erdészeti. De maga az aszfalt jó, nem ráz. 1 autó széles, szóval nem versenypálya, mert ha valaki jön szembe akkor nem fér el.

**Comment by nbali** [comment]
@Sp3EdeR na de várjál, ha nem tempós akkor mire? átvezetőre?

**Comment by Sp3EdeR** [comment]
Más osztotta meg, úgy tűnt mint amit érdemes lenne megnézni, ellenőrzendő, hogy érdekes-e. Lehet, hogy igen, lehet, hogy nem. Meg kéne nézni.
