### ISSUE TITLE
[NEW ROUTE] Oroszlány - Csákvár

### ISSUE THREAD

**Issue by nbali** [Sp3EdeR/huroutes#6]
https://www.google.com/maps/dir/Oroszl%C3%A1ny,+Majk-k%C3%B6z%C3%A9ps%C5%91+malom,+2840/Cs%C3%A1kv%C3%A1r/@47.4492402,18.3276888,12z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x476a3ec5c6f37bef:0xf70de196866d39c8!2m2!1d18.3352124!2d47.5040641!1m5!1m1!1s0x476a172111a09eef:0xadc31c32fbb437aa!2m2!1d18.4602445!2d47.3941468!3e0

**Comment by Sp3EdeR** [comment]
Kipróbáltuk az útvonalat és nincs semmi élvezeti faktora sajnos. Úgyhogy szerintem ezt zárom.
