### ISSUE TITLE
[NEW ROUTE] Hollóháza - Kéked

### ISSUE THREAD

**Issue by Sp3EdeR** [Sp3EdeR/huroutes#60]
Ismeretlen út, de érdekesnek néz ki. Közepes-jó útminőségnek látszik és jó kanyarok vannak benne

**Comment by LukreciaBabis** [comment]
Nagyon jó kanyarok vannak ott! Havi szinten járunk arra, az út minősége helyenként pocsék, ott le kell lassulni. A Hollóháza - Kéked szakasz elég rövid és kevésbé kacskaringós, de ha tovább megyünk Abaújvár felé, ott több és jobb kanyar is van (sokkal jobban megéri tovább menni), bár az út minősége romlik és néhány falun át kell menni. + Zsujta után tovább lehet menni Göncre és Telkibányára is, így egy kört leírva (tehát valahogy így nézne ki a kör, ha Göncről indulunk: Gönc - Telkibánya - Pálháza - Filkeháza - Füzérkomlós - Hollóháza - Kéked - Abaújvár - Zsujta és innen visszatérünk a Gönc felé vezető kereszteződéshez).

**Comment by Sp3EdeR** [comment]
Térkép alapján a Hollóháza és Kéked közti szakaszban van a csomó élesebb kanyar. Viszont Kéked és Abaújvár között mindössze pár enyhe kanyar látszik. Biztosan arra gondoltál?

A Gönctől Pálházáig vezető szakaszt már [felvettük a huroutes-ra](https://sp3eder.github.io/huroutes/#3708), ez a hibajegy nem arról szól, hanem kifejezetten a hiányzó Hollóháza - Kéked közti szakaszról csak.
