### ISSUE TITLE
[NEW ROUTE] 2303 (Mátraszele)

### ISSUE THREAD

**Issue by Sp3EdeR** [Sp3EdeR/huroutes#67]
A Ceredi szerpentin végénél egy enyhén kanyargós, egész jó útminőségű szakasznak tűnik.
https://goo.gl/maps/uDhRsjFDw7u6QgCk8

**Comment by nbali** [comment]
valóban az @Sp3EdeR - 2021-09-12 arra mentünk

**Comment by nbali** [comment]
@Sp3EdeR Mátraszele után Rákóczibányánál álltunk meg

2021-09-12 
17:41:29: @nbali Na és akkor most nem Salgótarján fele ahogy mentünk, hanem a másik irányba.
17:41:37: @Sp3EdeR Aha.. Jólvan, nekem jó az... Waze is arra akarja hogy menjünk.
