### ISSUE TITLE
[ROUTE]: Csobánka - Pilisvörösvár

### ISSUE THREAD

**Issue by nbali** [Sp3EdeR/huroutes#69]
### The route's name / Az út neve

Csobánka - Pilisvörösvár

### The route / Az út

https://goo.gl/maps/u1PVEq2of38enZA18

### The route's description / Az útvonal leírása

Útminőség közepes, Forgalom közepes, Sok a szintváltozás, emiatt beláthatósága sokszor limitált

### Rating / Értékelés

5

### Last driven / Legutóbbi vezetés

2022 április

### The route's type / Az útvonal típusa

- [ ] Route is shown in the background / Háttérben mutatott útvonal

**Comment by Dpx86** [comment]
Trükkös az aszfalt, mert tud csúszós lenni! Vörösvárról Csobánkára talán jobb csapatni, mert több a felfelé vezető kanyar.
