### ISSUE TITLE
[ROUTE]: Füzérkomlós - Nyíri - Bózsva - királykút majd Telkibánya 

### ISSUE THREAD

**Issue by LukreciaBabis** [Sp3EdeR/huroutes#85]
### The route's name / Az út neve

Királykút 

### The route / Az út

Nem csatoltam 

### The route's description / Az útvonal leírása

Jelenleg javítják (2022 június eleje van most), közepes minőségű az út minősége. A látvány gyönyörű, könnyű kanyarok az erdőben / a hegyek között. A királykútnál van egy kisebb pihenő ahol meg lehet állni (kB 20-30 autónak van kényelmesen hely a parkolóban, de az út szélén is meg lehet állni) 

### Rating / Értékelés

8

### Last driven / Legutóbbi vezetés

1 napja 

### The route's type / Az útvonal típusa

- [ ] Route is shown in the background / Háttérben mutatott útvonal

**Comment by Sp3EdeR** [comment]
@LukreciaBabis írtam chaten ezzel kapcsolatban.

**Comment by Sp3EdeR** [comment]
Válasz hiányában zárom. Így nem használható ez az infó.
