### ISSUE TITLE
[ROUTE]: Tata - Tarján

### ISSUE THREAD

**Issue by Sp3EdeR** [Sp3EdeR/huroutes#94]
### The route's name / Az út neve

Tata - Tarján

### The route / Az út

csatolva

### The route's description / Az útvonal leírása

Szinte az egész útszakasz pillanatnyilag felújított és felújítás alatt áll (fel van marva). Pillanatnyilag nem autózható jól, de nemsokára igazán jó szakasz lesz belőle. Újra ki kell menni később, felderíteni ha kész a felújítás.

Enyhe kanyarokkal hömpölyög keresztül ez az út a Gerecsei Tájvédelmi körzeten erdőn-mezőn-földeken át. A dimbes-dombos táj segít feldobni az útvonalat helyenként némi emelkedővel és lejtővel is. Szép kilátásban gyönyörködhetünk az út mentén. A forgalom közepes-erős, de akad lehetőség előzni.

Útbaesik a szép [Agostyáni Arborétum](https://verteserdo.hu/latnivalok/agostyani-arboretum/), ahol meg lehet állni egy séta erejére. Ezen kívül megtekinthető a mészkőbánya egy [rövid sétával](https://goo.gl/maps/vieRKp2ES1nwUqjw9) a Gorba-tető pihenőhelyről.

Felvételkor érdemes megemlíteni / bekötni a [Gerecsei Bejáróútba](https://sp3eder.github.io/huroutes/#Gerecse).

### Rating / Értékelés

6

### Last driven / Legutóbbi vezetés

2022 július

### The route's type / Az útvonal típusa

- [ ] Route is shown in the background / Háttérben mutatott útvonal

**Comment by Sp3EdeR** [comment]
Route: [Tata - Tarján.zip](https://github.com/Sp3EdeR/huroutes/files/9067157/Tata.-.Tarjan.zip)

**Comment by nbali** [comment]
Az elején és végén is maradt eredeti aszfalt, és az új szakaszon nincs (még?) normális padka, cserébe valós a vadveszély.

**Comment by nbali** [comment]
Előzni kb viszont lehetetlen volt, illetve nem Tatáig húznám az utat hanem Agostyánig azután időpazarlás

**Comment by Sp3EdeR** [comment]
@nbali és erről fogsz írni a térképre? Mert úgy látom már csak az hiányzik! :)
